image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Deploy to S3 - build
        deployment: Test
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.4
            variables:
              AWS_ACCESS_KEY_ID: $EMAIL_PROJECTS_AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $EMAIL_PROJECTS_AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "eu-west-1"
              S3_BUCKET: "dk.responsive.website/$BITBUCKET_BRANCH"
              LOCAL_PATH: "."
              ACL: "public-read"
              EXTRA_ARGS: '--exclude=".git/*" --exclude="bitbucket-pipelines.yml"'
